version: '2'

services:
        letsencrypt:
                image: linuxserver/letsencrypt
                privileged: true
                ports:
                        - 443:443
                volumes:
                        - ./nginx/keys:/config/keys
                environment:
                        - EMAIL=nhhntr11@gmail.com
                        - URL=twocatus.org
                        - SUBDOMAINS=${HOSTNAME}
                        - TZ=America/Chicago
                        - ONLY_SUBDOMAINS=true
