version: '2'

services:
        mongodb:
                image: mongo
                ports:
                        - 27017:27017
                environment:
                        - MONGO_DATA_DIR=/data/db
                        - MONGO_LOG_DIR=/dev/null
                volumes:
                        - ./data/db:/data/db
                command: mongod --smallfiles --logpath=/dev/null # --quiet
                restart: always

        dws:
                image: ducatuscore-wallet-service
                ports:
                        - 3380:3380
                        - 3232:3232
                        - 3231:3231
                command: bash -c "npm start; tail -f /dev/random"
                restart: always
