version: '2'

services:
        mongodb:
                image: mongo
                environment:
                        - MONGO_DATA_DIR=/data/db
                        - MONGO_LOG_DIR=/dev/null
                volumes:
                        - mongodb-volume:/data/db
                command: mongod --smallfiles --logpath=/dev/null # --quiet
                restart: always

        dws:
                image: ducatuscore-wallet-service
                command: npm start
                ports:
                        - 3380:3380
                        - 3232:3232
                        - 3231:3231
                links:
                        - mongodb
                restart: always
                        
        nginx:
                image: nginx
                restart: always
                ports:
                        - 443:443
                volumes:
                        - ./nginx/conf.d:/etc/nginx/conf.d
                        - ./nginx/keys:/etc/nginx/keys
                links:
                        - dws
volumes:
        mongodb-volume:
